services:
  db: 
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: jc_short_link
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: